### ISSUE TITLE
Can not get the correct sound output after encode then decode?

### ISSUE THREAD

**Issue by idealx** [chrisballinger/OpusKit#1]
Build and run the example, just hear noise. Can you have a fixed version of code?

**Comment by chrisballinger** [comment]
I only got as far as garbled output and never finished it, sorry! If you
solve it please submit a pull request and I'll happily merge it :)

**Comment by idealx** [comment]
Never mind, thanks for you good work, I've solved it, I'll submit a pull request later when available :]

**Comment by chrisballinger** [comment]
@idealx awesome! What was wrong?

**Comment by idealx** [comment]
Just some wrong paramters passed, it's easy to find it. You can see diff of PR Later, thanks :]

**Comment by thangk48cc** [comment]
sorry men. but it can't decode right. and can't get voice

ORIGINAL DATA =  4090
opus data length: 383
opus DECODE length: 5760
